services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
  postgres:
    container_name: postgres
    image: postgres:12.6-alpine
    restart: always
    env_file:
      - .env
    environment: # 아래 환경변수를 추가하면 알아서 아래 내용을 만들어 줌
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
    ports:
      - "5432:5432"